### ISSUE TITLE
Parsejson library Version

### ISSUE THREAD

**Issue by tearodactyl** [zerocurrencycoin/Zero-Machine#1]
As reported by Github:

Known high severity security vulnerability detected in parsejson <=0.0.3 defined in package-lock.json.

**Comment by aacirino** [comment]
npm audit showed the issue to be in `parsejson`. Then I tried to fix the issue with `npm install parsejson@latest` but this is a know issue:

https://www.npmjs.com/advisories/528

It seems that we need to change the code to use `JSON.parse()` from Node.js

**Comment by aacirino** [comment]
Commit 9d5bf7e solved the issue
